#!/bin/sh
. /lib/functions.sh

# Get Device
if [[ $(cat /proc/cpuinfo | grep 'machine' | awk {'print $6'}) == "NANO" ]]; then
    device="NANO"
elif [[ $(cat /proc/cpuinfo | grep 'machine' | awk {'print $6'}) == "TETRA" ]]; then
    device="TETRA"
fi

[ "${ACTION}" = "pressed" ] && {
    /usr/bin/pineapple/blink &
}

[ "${ACTION}" = "released" ] || exit 0

killall blink
/sbin/led reset

if [ -f "/etc/pineapple/setupRequired" ]; then
    if [ -f /etc/pineapple/init ]; then
        exit
    fi

    if [ ! -f /tmp/button_setup ]; then
        if [ "$SEEN" -lt 2 ]; then
            logger "First Setup: Disable WiFi"
            wifi down
            ifconfig wlan0 down && ifconfig wlan0-1 down
            /sbin/led blue on
        else
            logger "First Setup: Keep WiFi On"
        fi
        touch /tmp/button_setup
    fi
    exit
fi

if [ "$SEEN" -lt 6 ]; then
    bash /etc/pineapple/button_script
else
    echo "FACTORY RESET" > /dev/console
    jffs2reset -y && reboot &
fi

return 0
